apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: demo
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 563763293556.dkr.ecr.us-east-1.amazonaws.com/webapp
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: demo
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: LoadBalancer  
  ports:
  - port: 80
    targetPort: 8080