cloudOne: 
    apiKey: 2fGTEp0ZW1o9zVpLBqIfQG0EZyu
    endpoint: https://container.sg-1.cloudone.trendmicro.com
    exclusion: 
        namespaces: [kube-system]
    runtimeSecurity:
        enabled: true
    vulnerabilityScanning:
        enabled: true
    inventoryCollection:
        enabled: true
