name: 'K8S Attacks'

on: 
  workflow_dispatch:
env:
  aws_region: us-east-1

jobs:
  attacks:
    name: Run Attacks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.aws_region }}
    - name: Run Attacks
      run: |
        cd k8s
        terraform init
        terraform output cluster_name > cluster_name
        export CLUSTER_NAME=$(cat cluster_name | tr -d '"')
        aws eks --region us-east-1 update-kubeconfig --name $CLUSTER_NAME
        ./script/attacker.sh